homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 40.0231
  longitude: -83.181
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 286
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml
  # Include package directory
  packages: !include_dir_named packages
  temperature_unit: F

logger:
  default: info

recorder:
  purge_interval: 1
  purge_keep_days: 20
  db_url: postgresql://pi:%5ED3w4aNd@localhost/homeassistant

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
#frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

ffmpeg:

mqtt:
  broker: 127.0.0.1

# display the map
#map:

#ios:

#notify:
#  - platform: ios
#    name: ios
#    target: '0048d58d-9e74-33a3-9825-ad33ad732086'

#automation:
#  - alias: "Startup Notification"
#    trigger:
#      platform: event
#      event_type: homeassistant_start
#    action:
#      service: notify.iOSApp
#      data:
#        message: "Home Assistant is back up! Yay!"

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
