ios:

notify:
  - platform: ios
    name: ios
    target: '0048d58d-9e74-33a3-9825-ad33ad732086'
  - platform: ios
    name: ios
    target: '6b348bae-9c01-36f9-ae5e-87fd88ef2c2b'

automation:
  - alias: "Startup Notification"
    trigger:
      platform: event
      event_type: homeassistant_start
    action:
      service: notify.ios_andys_iphone_x
      data:
        title: "Home Assistant"
        message: "Home Assistant is back up!"
        data: 
          push:
            badge: 5
