ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

sensor:
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - volume
      - last_motion

camera:
  - platform: ring
      
group:
  Ring Doorbell:
    entities:
      - sensor.ring_Front_Door_Battery
      - sensor.ring_front_door_volume
      - sensor.ring_Front_Door_Last_Activity
      - sensor.ring_Front_Door_Last_Motion
      - binary_sensor.ring_Front_Door_Motion
      - binary_sensor.ring_Front_Door_Ding

automation:

  - alias: 'announce someone at front door'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'off'
        to: 'on'

    action:
      - service: tts.google_say
        data:
          entity_id: media_player.default_speaker
          message: 'Attention! Someone is at the front door!'
      - service: notify.mypushbullet
        data_template:
          title: "Front door activity"
          message: "Attention! Someone is at the front door!"
