sensor:
  - platform: speedtest
    name: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

group:
  Speed Test:
    entities:
      - sensor.Speedtest_Ping
      - sensor.Speedtest_Upload
      - sensor.Speedtest_Download
