sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: last_boot
      - type: since_last_boot
      - type: processor_use

group:
  System Statistics:
    entities:
      - sensor.disk_use_percent_
      - sensor.memory_use_percent
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.processor_use
