automation:
  - alias: 'Test TTS Sound'
    trigger:
#      - platform: time
#        at: '17:15:00'
    action:
      service: tts.google_say
      data:
        entity_id: media_player.default_speaker
        message: 'Hi Layla Bug'


