sensor:
  # Google Travel Time
  - platform: google_travel_time
    name: Home to Work Downtown
    api_key: !secret google_distance_key
    origin: 4836 Heath Trails Rd Hilliard, OH 43026
    destination: One Nationwide Plaza Columbus, OH 43215

  - platform: google_travel_time
    name: Home to Work Dublin
    api_key: !secret google_distance_key
    origin: 4836 Heath Trails Rd Hilliard, OH 43026
    destination: 5525 Parkcenter Cir, C0-01-02, Dublin, OH 43017

group:
  Travel Time to Work:
    entities:
      - sensor.Home_to_Work_Downtown
      - sensor.Home_to_Work_Dublin
