homeassistant:
  customize:
    sensor.usps_mail:
      friendly_name: USPS Mail
    sensor.usps_packages:
      friendly_name: USPS Packages

group:
  USPS:
    entities:
      - sensor.usps_mail
      - sensor.usps_packages
      - camera.usps_mail_pictures

sensor:
  - platform: mqtt
    name: 'USPS Mail'
    state_topic: '/usps/mails'
    value_template: "{{ value }}"

  - platform: mqtt
    name: USPS Packages
    state_topic: '/usps/packages'
    value_template: "{{ value }}"

camera:
  - platform: generic
    name: USPS Mail Pictures
    still_image_url: 'http://192.168.1.91:8123/local/todays_mails.gif'
